#!/usr/bin/env bash

declare -x GITEA_MARKDOWN_ENABLE_HARD_LINE_BREAK
[[ -z "${GITEA_MARKDOWN_ENABLE_HARD_LINE_BREAK}" ]] && GITEA_MARKDOWN_ENABLE_HARD_LINE_BREAK="false"

declare -x GITEA_MARKDOWN_CUSTOM_URL_SCHEMES
[[ -z "${GITEA_MARKDOWN_CUSTOM_URL_SCHEMES}" ]] && GITEA_MARKDOWN_CUSTOM_URL_SCHEMES=""

declare -x GITEA_MARKDOWN_FILE_EXTENSIONS
[[ -z "${GITEA_MARKDOWN_FILE_EXTENSIONS}" ]] && GITEA_MARKDOWN_FILE_EXTENSIONS=".md,.markdown,.mdown,.mkd,"
