#!/usr/bin/env bash

declare -x GITEA_ATTACHMENT_ENABLED
[[ -z "${GITEA_ATTACHMENT_ENABLED}" ]] && GITEA_ATTACHMENT_ENABLED="true"

declare -x GITEA_ATTACHMENT_PATH
[[ -z "${GITEA_ATTACHMENT_PATH}" ]] && GITEA_ATTACHMENT_PATH="${GITEA_BASE_PATH}/attachments"

declare -x GITEA_ATTACHMENT_ALOWED_TYPES
[[ -z "${GITEA_ATTACHMENT_ALOWED_TYPES}" ]] && GITEA_ATTACHMENT_ALOWED_TYPES="image/jpeg|image/png|application/zip|application/gzip"

declare -x GITEA_ATTACHMENT_MAX_SIZE
[[ -z "${GITEA_ATTACHMENT_MAX_SIZE}" ]] && GITEA_ATTACHMENT_MAX_SIZE="5"

declare -x GITEA_ATTACHMENT_MAX_FILES
[[ -z "${GITEA_ATTACHMENT_MAX_FILES}" ]] && GITEA_ATTACHMENT_MAX_FILES="5"
