#!/usr/bin/env bash

declare -x GITEA_HEALTHCHECK_URL
[[ -z "${GITEA_HEALTHCHECK_URL}" ]] && GITEA_HEALTHCHECK_URL="${GITEA_SERVER_LOCAL_ROOT_URL}"

declare -x GITEA_HEALTHCHECK_CODE
[[ -z "${GITEA_HEALTHCHECK_CODE}" ]] && GITEA_HEALTHCHECK_CODE="200"
