#!/bin/bash

if [ ! -d /etc/ssh/keys ]
then
  mkdir -p /etc/ssh/keys
fi

if [ ! -f /etc/ssh/keys/ssh_host_ed25519_key ]
then
  echo "Generating /etc/ssh/keys/ssh_host_ed25519_key..."
  ssh-keygen -t ed25519 -b 4096 -f /etc/ssh/keys/ssh_host_ed25519_key -N "" > /dev/null
fi

if [ ! -f /etc/ssh/keys/ssh_host_rsa_key ]
then
  echo "Generating /etc/ssh/keys/ssh_host_rsa_key..."
  ssh-keygen -t rsa -b 2048 -f /etc/ssh/keys/ssh_host_rsa_key -N "" > /dev/null
fi

if [ ! -f /etc/ssh/keys/ssh_host_dsa_key ]
then
  echo "Generating /etc/ssh/keys/ssh_host_dsa_key..."
  ssh-keygen -t dsa -f /etc/ssh/keys/ssh_host_dsa_key -N "" > /dev/null
fi

if [ ! -f /etc/ssh/keys/ssh_host_ecdsa_key ]
then
  echo "Generating /etc/ssh/keys/ssh_host_ecdsa_key..."
  ssh-keygen -t ecdsa -b 256 -f /etc/ssh/keys/ssh_host_ecdsa_key -N "" > /dev/null
fi
