#!/usr/bin/env bash

declare -x GITEA_UI_EXPLORE_PAGING_NUM
[[ -z "${GITEA_UI_EXPLORE_PAGING_NUM}" ]] && GITEA_UI_EXPLORE_PAGING_NUM="20"

declare -x GITEA_UI_ISSUE_PAGING_NUM
[[ -z "${GITEA_UI_ISSUE_PAGING_NUM}" ]] && GITEA_UI_ISSUE_PAGING_NUM="10"

declare -x GITEA_UI_FEED_MAX_COMMIT_NUM
[[ -z "${GITEA_UI_FEED_MAX_COMMIT_NUM}" ]] && GITEA_UI_FEED_MAX_COMMIT_NUM="5"

declare -x GITEA_UI_GRAPH_MAX_COMMIT_NUM
[[ -z "${GITEA_UI_GRAPH_MAX_COMMIT_NUM}" ]] && GITEA_UI_GRAPH_MAX_COMMIT_NUM="100"

declare -x GITEA_UI_CODE_COMMENT_LINES
[[ -z "${GITEA_UI_CODE_COMMENT_LINES}" ]] && GITEA_UI_CODE_COMMENT_LINES="4"

declare -x GITEA_UI_THEME_COLOR_META_TAG
[[ -z "${GITEA_UI_THEME_COLOR_META_TAG}" ]] && GITEA_UI_THEME_COLOR_META_TAG="6cc644"

declare -x GITEA_MAX_DISPLAY_FILE_SIZE
[[ -z "${GITEA_MAX_DISPLAY_FILE_SIZE}" ]] && GITEA_MAX_DISPLAY_FILE_SIZE="8388608"

declare -x GITEA_UI_SHOW_USER_EMAIL
[[ -z "${GITEA_UI_SHOW_USER_EMAIL}" ]] && GITEA_UI_SHOW_USER_EMAIL="true"

declare -x GITEA_UI_DEFAULT_THEME
[[ -z "${GITEA_UI_DEFAULT_THEME}" ]] && GITEA_UI_DEFAULT_THEME="gitea"

declare -x GITEA_UI_THEMES
[[ -z "${GITEA_UI_THEMES}" ]] && GITEA_UI_THEMES="gitea,arc-green"

declare -x GITEA_UI_DEFAULT_SHOW_FULL_NAME
[[ -z "${GITEA_UI_DEFAULT_SHOW_FULL_NAME}" ]] && GITEA_UI_DEFAULT_SHOW_FULL_NAME="false"

declare -x GITEA_UI_SEARCH_REPO_DESCRIPTION
[[ -z "${GITEA_UI_SEARCH_REPO_DESCRIPTION}" ]] && GITEA_UI_SEARCH_REPO_DESCRIPTION="true"

declare -x GITEA_UI_ADMIN_USER_PAGING_NUM
[[ -z "${GITEA_UI_ADMIN_USER_PAGING_NUM}" ]] && GITEA_UI_ADMIN_USER_PAGING_NUM="50"

declare -x GITEA_UI_ADMIN_REPO_PAGING_NUM
[[ -z "${GITEA_UI_ADMIN_REPO_PAGING_NUM}" ]] && GITEA_UI_ADMIN_REPO_PAGING_NUM="50"

declare -x GITEA_UI_ADMIN_NOTICE_PAGING_NUM
[[ -z "${GITEA_UI_ADMIN_NOTICE_PAGING_NUM}" ]] && GITEA_UI_ADMIN_NOTICE_PAGING_NUM="50"

declare -x GITEA_UI_ADMIN_ORG_PAGING_NUM
[[ -z "${GITEA_UI_ADMIN_ORG_PAGING_NUM}" ]] && GITEA_UI_ADMIN_ORG_PAGING_NUM="50"

declare -x GITEA_UI_USER_REPO_PAGING_NUM
[[ -z "${GITEA_UI_USER_REPO_PAGING_NUM}" ]] && GITEA_UI_USER_REPO_PAGING_NUM="15"

declare -x GITEA_UI_META_AUTHOR
[[ -z "${GITEA_UI_META_AUTHOR}" ]] && GITEA_UI_META_AUTHOR="Gitea - Git with a cup of tea"

declare -x GITEA_UI_META_DESCRIPTION
[[ -z "${GITEA_UI_META_DESCRIPTION}" ]] && GITEA_UI_META_DESCRIPTION="Gitea (Git with a cup of tea) is a painless self-hosted Git service written in Go"

declare -x GITEA_UI_META_KEYWORDS
[[ -z "${GITEA_UI_META_KEYWORDS}" ]] && GITEA_UI_META_KEYWORDS="go,git,self-hosted,gitea"
