#!/usr/bin/env bash

declare -x GITEA_SSH_MINIMUM_KEY_SIZES_ED25519
[[ -z "${GITEA_SSH_MINIMUM_KEY_SIZES_ED25519}" ]] && GITEA_SSH_MINIMUM_KEY_SIZES_ED25519="256"

declare -x GITEA_SSH_MINIMUM_KEY_SIZES_ECDSA
[[ -z "${GITEA_SSH_MINIMUM_KEY_SIZES_ECDSA}" ]] && GITEA_SSH_MINIMUM_KEY_SIZES_ECDSA="256"

declare -x GITEA_SSH_MINIMUM_KEY_SIZES_RSA
[[ -z "${GITEA_SSH_MINIMUM_KEY_SIZES_RSA}" ]] && GITEA_SSH_MINIMUM_KEY_SIZES_RSA="2048"

declare -x GITEA_SSH_MINIMUM_KEY_SIZES_DSA
[[ -z "${GITEA_SSH_MINIMUM_KEY_SIZES_DSA}" ]] && GITEA_SSH_MINIMUM_KEY_SIZES_DSA="1024"
