#!/usr/bin/env bash

declare -x GITEA_ADMIN_DISABLE_REGULAR_ORG_CREATION
[[ -z "${GITEA_ADMIN_DISABLE_REGULAR_ORG_CREATION}" ]] && GITEA_ADMIN_DISABLE_REGULAR_ORG_CREATION="false"

declare -x GITEA_ADMIN_DEFAULT_EMAIL_NOTIFICATIONS
[[ -z "${GITEA_ADMIN_DEFAULT_EMAIL_NOTIFICATIONS}" ]] && GITEA_ADMIN_DEFAULT_EMAIL_NOTIFICATIONS="enabled"
