FROM webhippie/golang:1.26-amd64@sha256:3fb3f7cf9ac2237b439a413416576fdd41390aeca0f75ef0c2fd3c3ee9700376 as build

ENV GITEA_PATH code.gitea.io/gitea
ENV GITEA_REPO https://github.com/go-gitea/gitea.git
ENV GITEA_BRANCH release/v1.12

RUN apk update && \
  apk upgrade && \
  apk add nodejs npm && \
  git clone -b ${GITEA_BRANCH} ${GITEA_REPO} /srv/app/src/${GITEA_PATH} && \
  cd /srv/app/src/${GITEA_PATH} && \
  TAGS="bindata sqlite" make build install

FROM webhippie/alpine:latest-amd64@sha256:b8c8a2164aa640092a989d87ae81f820d69de2f9d24134ca2f4223877487ccd5

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Gitea" \
  org.label-schema.version="latest" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 3000 22

VOLUME ["/var/lib/gitea", "/var/log/gitea", "/usr/share/gitea"]
WORKDIR /var/lib/gitea
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  apk add git git-lfs asciidoc openssh-keygen && \
  mkdir -p /var/lib/gitea && \
  groupadd -g 1000 git && \
  useradd -u 1000 -d /var/lib/gitea -g git -s /bin/bash -M -p '*' git && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/gitea /usr/bin/gitea
COPY ./overlay ./overlay-amd64 /
