#!/usr/bin/env bash

declare -x GITEA_REPO_ROOT
[[ -z "${GITEA_REPO_ROOT}" ]] && GITEA_REPO_ROOT="${GITEA_BASE_PATH}/repos"

declare -x GITEA_REPO_SCRIPT_TYPE
[[ -z "${GITEA_REPO_SCRIPT_TYPE}" ]] && GITEA_REPO_SCRIPT_TYPE="bash"

declare -x GITEA_REPO_ANSI_CHARSET
[[ -z "${GITEA_REPO_ANSI_CHARSET}" ]] && GITEA_REPO_ANSI_CHARSET=""

declare -x GITEA_REPO_FORCE_PRIVATE
[[ -z "${GITEA_REPO_FORCE_PRIVATE}" ]] && GITEA_REPO_FORCE_PRIVATE="false"

declare -x GITEA_REPO_DEFAULT_PRIVATE
[[ -z "${GITEA_REPO_DEFAULT_PRIVATE}" ]] && GITEA_REPO_DEFAULT_PRIVATE="last"

declare -x GITEA_REPO_MAX_CREATION_LIMIT
[[ -z "${GITEA_REPO_MAX_CREATION_LIMIT}" ]] && GITEA_REPO_MAX_CREATION_LIMIT="-1"

declare -x GITEA_REPO_MIRROR_QUEUE_LENGTH
[[ -z "${GITEA_REPO_MIRROR_QUEUE_LENGTH}" ]] && GITEA_REPO_MIRROR_QUEUE_LENGTH="1000"

declare -x GITEA_REPO_PULL_REQUEST_QUEUE_LENGTH
[[ -z "${GITEA_REPO_PULL_REQUEST_QUEUE_LENGTH}" ]] && GITEA_REPO_PULL_REQUEST_QUEUE_LENGTH="1000"

declare -x GITEA_REPO_PREFERRED_LICENSES
[[ -z "${GITEA_REPO_PREFERRED_LICENSES}" ]] && GITEA_REPO_PREFERRED_LICENSES="Apache License 2.0,MIT License"

declare -x GITEA_REPO_DISABLE_HTTP_GIT
[[ -z "${GITEA_REPO_DISABLE_HTTP_GIT}" ]] && GITEA_REPO_DISABLE_HTTP_GIT="false"

declare -x GITEA_REPO_ACCESS_CONTROL_ALLOW_ORIGIN
[[ -z "${GITEA_REPO_ACCESS_CONTROL_ALLOW_ORIGIN}" ]] && GITEA_REPO_ACCESS_CONTROL_ALLOW_ORIGIN=""

declare -x GITEA_REPO_USE_COMPAT_SSH_URI
[[ -z "${GITEA_REPO_USE_COMPAT_SSH_URI}" ]] && GITEA_REPO_USE_COMPAT_SSH_URI="false"

declare -x GITEA_REPO_DEFAULT_CLOSE_ISSUES_VIA_COMMITS_IN_ANY_BRANCH
[[ -z "${GITEA_REPO_DEFAULT_CLOSE_ISSUES_VIA_COMMITS_IN_ANY_BRANCH}" ]] && GITEA_REPO_DEFAULT_CLOSE_ISSUES_VIA_COMMITS_IN_ANY_BRANCH="false"

declare -x GITEA_REPO_EDITOR_LINE_WRAP_EXTENSIONS
[[ -z "${GITEA_REPO_EDITOR_LINE_WRAP_EXTENSIONS}" ]] && GITEA_REPO_EDITOR_LINE_WRAP_EXTENSIONS=".txt,.md,.markdown,.mdown,.mkd"

declare -x GITEA_REPO_EDITOR_PREVIEWABLE_FILE_MODES
[[ -z "${GITEA_REPO_EDITOR_PREVIEWABLE_FILE_MODES}" ]] && GITEA_REPO_EDITOR_PREVIEWABLE_FILE_MODES="markdown"

declare -x GITEA_REPO_LOCAL_LOCAL_COPY_PATH
[[ -z "${GITEA_REPO_LOCAL_LOCAL_COPY_PATH}" ]] && GITEA_REPO_LOCAL_LOCAL_COPY_PATH="/tmp/gitea/repo"

declare -x GITEA_REPO_LOCAL_LOCAL_WIKI_PATH
[[ -z "${GITEA_REPO_LOCAL_LOCAL_WIKI_PATH}" ]] && GITEA_REPO_LOCAL_LOCAL_WIKI_PATH="/tmp/gitea/wiki"

declare -x GITEA_REPO_UPLOAD_ENABLED
[[ -z "${GITEA_REPO_UPLOAD_ENABLED}" ]] && GITEA_REPO_UPLOAD_ENABLED="true"

declare -x GITEA_REPO_UPLOAD_TEMP_PATH
[[ -z "${GITEA_REPO_UPLOAD_TEMP_PATH}" ]] && GITEA_REPO_UPLOAD_TEMP_PATH="/tmp/gitea/upload"

declare -x GITEA_REPO_UPLOAD_ALLOWED_TYPES
[[ -z "${GITEA_REPO_UPLOAD_ALLOWED_TYPES}" ]] && GITEA_REPO_UPLOAD_ALLOWED_TYPES=""

declare -x GITEA_REPO_UPLOAD_FILE_MAX_SIZE
[[ -z "${GITEA_REPO_UPLOAD_FILE_MAX_SIZE}" ]] && GITEA_REPO_UPLOAD_FILE_MAX_SIZE="3"

declare -x GITEA_REPO_UPLOAD_MAX_FILES
[[ -z "${GITEA_REPO_UPLOAD_MAX_FILES}" ]] && GITEA_REPO_UPLOAD_MAX_FILES="5"

declare -x GITEA_REPO_PULL_REQUEST_WIP_PREFIXES
[[ -z "${GITEA_REPO_PULL_REQUEST_WIP_PREFIXES}" ]] && GITEA_REPO_PULL_REQUEST_WIP_PREFIXES="WIP:,[WIP]"

declare -x GITEA_REPO_ISSUE_LOCK_REASONS
[[ -z "${GITEA_REPO_ISSUE_LOCK_REASONS}" ]] && GITEA_REPO_ISSUE_LOCK_REASONS="Heated,Offtopic,Resolved,Spam"
