#!/usr/bin/env bash

declare -x GITEA_WEBHOOK_QUEUE_LENGTH
[[ -z "${GITEA_WEBHOOK_QUEUE_LENGTH}" ]] && GITEA_WEBHOOK_QUEUE_LENGTH="1000"

declare -x GITEA_WEBHOOK_DELIVER_TIMEOUT
[[ -z "${GITEA_WEBHOOK_DELIVER_TIMEOUT}" ]] && GITEA_WEBHOOK_DELIVER_TIMEOUT="5"

declare -x GITEA_WEBHOOK_SKIP_TLS_VERIFY
[[ -z "${GITEA_WEBHOOK_SKIP_TLS_VERIFY}" ]] && GITEA_WEBHOOK_SKIP_TLS_VERIFY="false"

declare -x GITEA_WEBHOOK_PAGING_NUM
[[ -z "${GITEA_WEBHOOK_PAGING_NUM}" ]] && GITEA_WEBHOOK_PAGING_NUM="10"
