#!/usr/bin/env bash

declare -x GITEA_SESSION_PROVIDER_CONFIG
[[ -z "${GITEA_SESSION_PROVIDER_CONFIG}" ]] && GITEA_SESSION_PROVIDER_CONFIG="${GITEA_SESSION_PATH}"

declare -x GITEA_SESSION_COOKIE_NAME
[[ -z "${GITEA_SESSION_COOKIE_NAME}" ]] && GITEA_SESSION_COOKIE_NAME="gitea"

declare -x GITEA_SESSION_COOKIE_SECURE
[[ -z "${GITEA_SESSION_COOKIE_SECURE}" ]] && GITEA_SESSION_COOKIE_SECURE="false"

declare -x GITEA_SESSION_ENABLE_SET_COOKIE
[[ -z "${GITEA_SESSION_ENABLE_SET_COOKIE}" ]] && GITEA_SESSION_ENABLE_SET_COOKIE="true"

declare -x GITEA_SESSION_GC_INTERVAL_TIME
[[ -z "${GITEA_SESSION_GC_INTERVAL_TIME}" ]] && GITEA_SESSION_GC_INTERVAL_TIME="86400"

declare -x GITEA_SESSION_SESSION_LIFE_TIME
[[ -z "${GITEA_SESSION_SESSION_LIFE_TIME}" ]] && GITEA_SESSION_SESSION_LIFE_TIME="86400"

declare -x GITEA_SESSION_WAIT_FOR_FAIL
[[ -z "${GITEA_SESSION_WAIT_FOR_FAIL}" ]] && GITEA_SESSION_WAIT_FOR_FAIL="true"

declare -x GITEA_SESSION_PROVIDER
[[ -z "${GITEA_SESSION_PROVIDER}" ]] && GITEA_SESSION_PROVIDER="memory"

declare -x GITEA_SESSION_PATH
[[ -z "${GITEA_SESSION_PATH}" ]] && GITEA_SESSION_PATH="${GITEA_BASE_PATH}/sessions"

declare -x GITEA_SESSION_REDIS_HOST
[[ -z "${GITEA_SESSION_REDIS_HOST}" ]] && GITEA_SESSION_REDIS_HOST="redis:6379"

declare -x GITEA_SESSION_REDIS_PASSWORD
[[ -z "${GITEA_SESSION_REDIS_PASSWORD}" ]] && GITEA_SESSION_REDIS_PASSWORD=""

declare -x GITEA_SESSION_REDIS_DB
[[ -z "${GITEA_SESSION_REDIS_DB}" ]] && GITEA_SESSION_REDIS_DB="1"

declare -x GITEA_SESSION_REDIS_POOL_SIZE
[[ -z "${GITEA_SESSION_REDIS_POOL_SIZE}" ]] && GITEA_SESSION_REDIS_POOL_SIZE="100"

declare -x GITEA_SESSION_REDIS_IDLE_TIMEOUT
[[ -z "${GITEA_SESSION_REDIS_IDLE_TIMEOUT}" ]] && GITEA_SESSION_REDIS_IDLE_TIMEOUT="180"
