#!/usr/bin/env bash

declare -x GITEA_OAUTH2_ENABLED
[[ -z "${GITEA_OAUTH2_ENABLED}" ]] && GITEA_OAUTH2_ENABLED="true"

declare -x GITEA_OAUTH2_ACCESS_TOKEN_EXPIRATION_TIME
[[ -z "${GITEA_OAUTH2_ACCESS_TOKEN_EXPIRATION_TIME}" ]] && GITEA_OAUTH2_ACCESS_TOKEN_EXPIRATION_TIME="3600"

declare -x GITEA_OAUTH2_REFRESH_TOKEN_EXPIRATION_TIME
[[ -z "${GITEA_OAUTH2_REFRESH_TOKEN_EXPIRATION_TIME}" ]] && GITEA_OAUTH2_REFRESH_TOKEN_EXPIRATION_TIME="730"

declare -x GITEA_OAUTH2_INVALIDATE_REFRESH_TOKENS
[[ -z "${GITEA_OAUTH2_INVALIDATE_REFRESH_TOKENS}" ]] && GITEA_OAUTH2_INVALIDATE_REFRESH_TOKENS="false"

declare -x GITEA_OAUTH2_JWT_SECRET
[[ -z "${GITEA_OAUTH2_JWT_SECRET}" ]] && GITEA_OAUTH2_JWT_SECRET=""
