#!/usr/bin/env bash

declare -x GITEA_DATABASE_WAIT_FOR_FAIL
[[ -z "${GITEA_DATABASE_WAIT_FOR_FAIL}" ]] && GITEA_DATABASE_WAIT_FOR_FAIL="true"

declare -x GITEA_DATABASE_ITERATE_BUFFER_SIZE
[[ -z "${GITEA_DATABASE_ITERATE_BUFFER_SIZE}" ]] && GITEA_DATABASE_ITERATE_BUFFER_SIZE="50"

declare -x GITEA_DATABASE_LOG_SQL
[[ -z "${GITEA_DATABASE_LOG_SQL}" ]] && GITEA_DATABASE_LOG_SQL="false"

declare -x GITEA_DATABASE_RETRIES
[[ -z "${GITEA_DATABASE_RETRIES}" ]] && GITEA_DATABASE_RETRIES="10"

declare -x GITEA_DATABASE_RETRY_BACKOFF
[[ -z "${GITEA_DATABASE_RETRY_BACKOFF}" ]] && GITEA_DATABASE_RETRY_BACKOFF="3s"

declare -x GITEA_DATABASE_TYPE
[[ -z "${GITEA_DATABASE_TYPE}" ]] && GITEA_DATABASE_TYPE="sqlite3"

case "${GITEA_DATABASE_TYPE}" in
	"mysql")
		declare -x GITEA_DATABASE_HOST
		[[ -z "${GITEA_DATABASE_HOST}" ]] && GITEA_DATABASE_HOST="mysql:3306"

		declare -x GITEA_DATABASE_NAME
		[[ -z "${GITEA_DATABASE_NAME}" ]] && GITEA_DATABASE_NAME="gitea"

		declare -x GITEA_DATABASE_USERNAME
		[[ -z "${GITEA_DATABASE_USERNAME}" ]] && GITEA_DATABASE_USERNAME="root"

		declare -x GITEA_DATABASE_PASSWORD
		[[ -z "${GITEA_DATABASE_PASSWORD}" ]] && GITEA_DATABASE_PASSWORD=""

		declare -x GITEA_DATABASE_SSL
		[[ -z "${GITEA_DATABASE_SSL}" ]] && GITEA_DATABASE_SSL="false"

		declare -x GITEA_DATABASE_CHARSET
		[[ -z "${GITEA_DATABASE_CHARSET}" ]] && GITEA_DATABASE_CHARSET="utf8"
		;;
	"postgres")
		declare -x GITEA_DATABASE_HOST
		[[ -z "${GITEA_DATABASE_HOST}" ]] && GITEA_DATABASE_HOST="postgres:5432"

		declare -x GITEA_DATABASE_NAME
		[[ -z "${GITEA_DATABASE_NAME}" ]] && GITEA_DATABASE_NAME="gitea"

		declare -x GITEA_DATABASE_USERNAME
		[[ -z "${GITEA_DATABASE_USERNAME}" ]] && GITEA_DATABASE_USERNAME="postgres"

		declare -x GITEA_DATABASE_PASSWORD
		[[ -z "${GITEA_DATABASE_PASSWORD}" ]] && GITEA_DATABASE_PASSWORD=""

		declare -x GITEA_DATABASE_SSL
		[[ -z "${GITEA_DATABASE_SSL}" ]] && GITEA_DATABASE_SSL="disable"
		;;
	"sqlite3")
		declare -x GITEA_DATABASE_PATH
		[[ -z "${GITEA_DATABASE_PATH}" ]] && GITEA_DATABASE_PATH="${GITEA_SERVER_APP_DATA_PATH}/gitea.sqlite3"

		declare -x GITEA_DATABASE_TIMEOUT
		[[ -z "${GITEA_DATABASE_TIMEOUT}" ]] && GITEA_DATABASE_TIMEOUT="500"
		;;
esac
