#!/usr/bin/env bash

declare -x GITEA_CACHE_ADAPTER
[[ -z "${GITEA_CACHE_ADAPTER}" ]] && GITEA_CACHE_ADAPTER="memory"

declare -x GITEA_CACHE_WAIT_FOR_FAIL
[[ -z "${GITEA_CACHE_WAIT_FOR_FAIL}" ]] && GITEA_CACHE_WAIT_FOR_FAIL="true"

declare -x GITEA_CACHE_MEMCACHE_HOST
[[ -z "${GITEA_CACHE_MEMCACHE_HOST}" ]] && GITEA_CACHE_MEMCACHE_HOST="memcached:11211"

declare -x GITEA_CACHE_REDIS_HOST
[[ -z "${GITEA_CACHE_REDIS_HOST}" ]] && GITEA_CACHE_REDIS_HOST="redis:6379"

declare -x GITEA_CACHE_REDIS_PASSWORD
[[ -z "${GITEA_CACHE_REDIS_PASSWORD}" ]] && GITEA_CACHE_REDIS_PASSWORD=""

declare -x GITEA_CACHE_REDIS_DB
[[ -z "${GITEA_CACHE_REDIS_DB}" ]] && GITEA_CACHE_REDIS_DB="0"

declare -x GITEA_CACHE_REDIS_POOL_SIZE
[[ -z "${GITEA_CACHE_REDIS_POOL_SIZE}" ]] && GITEA_CACHE_REDIS_POOL_SIZE="100"

declare -x GITEA_CACHE_REDIS_IDLE_TIMEOUT
[[ -z "${GITEA_CACHE_REDIS_IDLE_TIMEOUT}" ]] && GITEA_CACHE_REDIS_IDLE_TIMEOUT="180"

declare -x GITEA_CACHE_INTERVAL
[[ -z "${GITEA_CACHE_INTERVAL}" ]] && GITEA_CACHE_INTERVAL="60"

declare -x GITEA_CACHE_ITEM_TTL
[[ -z "${GITEA_CACHE_ITEM_TTL}" ]] && GITEA_CACHE_ITEM_TTL="16h"
