#!/usr/bin/env bash

declare -x GITEA_API_ENABLE_SWAGGER
[[ -z "${GITEA_API_ENABLE_SWAGGER}" ]] && GITEA_API_ENABLE_SWAGGER="true"

declare -x GITEA_API_MAX_RESPONSE_ITEMS
[[ -z "${GITEA_API_MAX_RESPONSE_ITEMS}" ]] && GITEA_API_MAX_RESPONSE_ITEMS="50"

declare -x GITEA_API_DEFAULT_PAGING_NUM
[[ -z "${GITEA_API_DEFAULT_PAGING_NUM}" ]] && GITEA_API_DEFAULT_PAGING_NUM="30"

declare -x GITEA_API_DEFAULT_GIT_TREES_PER_PAGE
[[ -z "${GITEA_API_DEFAULT_GIT_TREES_PER_PAGE}" ]] && GITEA_API_DEFAULT_GIT_TREES_PER_PAGE="1000"
