#!/usr/bin/env bash

declare -x GITEA_INDEXER_PATH
[[ -z "${GITEA_INDEXER_PATH}" ]] && GITEA_INDEXER_PATH="${GITEA_BASE_PATH}/indexers"

declare -x GITEA_INDEXER_ISSUE_TYPE
[[ -z "${GITEA_INDEXER_ISSUE_TYPE}" ]] && GITEA_INDEXER_ISSUE_TYPE="bleve"

declare -x GITEA_INDEXER_ISSUE_PATH
[[ -z "${GITEA_INDEXER_ISSUE_PATH}" ]] && GITEA_INDEXER_ISSUE_PATH="${GITEA_INDEXER_PATH}/issues.bleve"

declare -x GITEA_INDEXER_ISSUE_QUEUE_TYPE
[[ -z "${GITEA_INDEXER_ISSUE_QUEUE_TYPE}" ]] && GITEA_INDEXER_ISSUE_QUEUE_TYPE="levelqueue"

declare -x GITEA_INDEXER_ISSUE_QUEUE_PATH
[[ -z "${GITEA_INDEXER_ISSUE_QUEUE_PATH}" ]] && GITEA_INDEXER_ISSUE_QUEUE_PATH="${GITEA_INDEXER_PATH}/issues.queue"

declare -x GITEA_INDEXER_ISSUE_QUEUE_BATCH_NUMBER
[[ -z "${GITEA_INDEXER_ISSUE_QUEUE_BATCH_NUMBER}" ]] && GITEA_INDEXER_ISSUE_QUEUE_BATCH_NUMBER="20"

declare -x GITEA_INDEXER_REPO_ENABLED
[[ -z "${GITEA_INDEXER_REPO_ENABLED}" ]] && GITEA_INDEXER_REPO_ENABLED="false"

declare -x GITEA_INDEXER_REPO_PATH
[[ -z "${GITEA_INDEXER_REPO_PATH}" ]] && GITEA_INDEXER_REPO_PATH="${GITEA_INDEXER_PATH}/repos.bleve"

declare -x GITEA_INDEXER_UPDATE_BUFFER_LEN
[[ -z "${GITEA_INDEXER_UPDATE_BUFFER_LEN}" ]] && GITEA_INDEXER_UPDATE_BUFFER_LEN="20"

declare -x GITEA_INDEXER_MAX_FILE_SIZE
[[ -z "${GITEA_INDEXER_MAX_FILE_SIZE}" ]] && GITEA_INDEXER_MAX_FILE_SIZE="1048576"

declare -x GITEA_INDEXER_REPO_INCLUDE
[[ -z "${GITEA_INDEXER_REPO_INCLUDE}" ]] && GITEA_INDEXER_REPO_INCLUDE=""

declare -x GITEA_INDEXER_REPO_EXCLUDE
[[ -z "${GITEA_INDEXER_REPO_EXCLUDE}" ]] && GITEA_INDEXER_REPO_EXCLUDE=""

declare -x GITEA_INDEXER_REDIS_HOST
[[ -z "${GITEA_INDEXER_REDIS_HOST}" ]] && GITEA_INDEXER_REDIS_HOST="redis:6379"

declare -x GITEA_INDEXER_REDIS_PASSWORD
[[ -z "${GITEA_INDEXER_REDIS_PASSWORD}" ]] && GITEA_INDEXER_REDIS_PASSWORD=""

declare -x GITEA_INDEXER_REDIS_DB
[[ -z "${GITEA_INDEXER_REDIS_DB}" ]] && GITEA_INDEXER_REDIS_DB="0"
