#!/usr/bin/env bash

declare -x GITEA_SECURITY_INSTALL_LOCK
[[ -z "${GITEA_SECURITY_INSTALL_LOCK}" ]] && GITEA_SECURITY_INSTALL_LOCK="true"

declare -x GITEA_SECURITY_SECRET_KEY
[[ -z "${GITEA_SECURITY_SECRET_KEY}" ]] && GITEA_SECURITY_SECRET_KEY=""

declare -x GITEA_SECURITY_LOGIN_REMEMBER_DAYS
[[ -z "${GITEA_SECURITY_LOGIN_REMEMBER_DAYS}" ]] && GITEA_SECURITY_LOGIN_REMEMBER_DAYS="7"

declare -x GITEA_SECURITY_COOKIE_USERNAME
[[ -z "${GITEA_SECURITY_COOKIE_USERNAME}" ]] && GITEA_SECURITY_COOKIE_USERNAME="gitea-username"

declare -x GITEA_SECURITY_COOKIE_REMEMBER_NAME
[[ -z "${GITEA_SECURITY_COOKIE_REMEMBER_NAME}" ]] && GITEA_SECURITY_COOKIE_REMEMBER_NAME="gitea-remember"

declare -x GITEA_SECURITY_REVERSE_PROXY_AUTHENTICATION_USER
[[ -z "${GITEA_SECURITY_REVERSE_PROXY_AUTHENTICATION_USER}" ]] && GITEA_SECURITY_REVERSE_PROXY_AUTHENTICATION_USER="X-WEBAUTH-USER"

declare -x GITEA_SECURITY_REVERSE_PROXY_AUTHENTICATION_EMAIL
[[ -z "${GITEA_SECURITY_REVERSE_PROXY_AUTHENTICATION_EMAIL}" ]] && GITEA_SECURITY_REVERSE_PROXY_AUTHENTICATION_EMAIL="X-WEBAUTH-EMAIL"

declare -x GITEA_SECURITY_MIN_PASSWORD_LENGTH
[[ -z "${GITEA_SECURITY_MIN_PASSWORD_LENGTH}" ]] && GITEA_SECURITY_MIN_PASSWORD_LENGTH="6"

declare -x GITEA_SECURITY_IMPORT_LOCAL_PATHS
[[ -z "${GITEA_SECURITY_IMPORT_LOCAL_PATHS}" ]] && GITEA_SECURITY_IMPORT_LOCAL_PATHS="false"

declare -x GITEA_SECURITY_DISABLE_GIT_HOOKS
[[ -z "${GITEA_SECURITY_DISABLE_GIT_HOOKS}" ]] && GITEA_SECURITY_DISABLE_GIT_HOOKS="false"

declare -x GITEA_SECURITY_PASSWORD_COMPLEXITY
[[ -z "${GITEA_SECURITY_PASSWORD_COMPLEXITY}" ]] && GITEA_SECURITY_PASSWORD_COMPLEXITY="lower,upper,digit"

declare -x GITEA_SECURITY_PASSWORD_HASH_ALGO
[[ -z "${GITEA_SECURITY_PASSWORD_HASH_ALGO}" ]] && GITEA_SECURITY_PASSWORD_HASH_ALGO="pbkdf2"

declare -x GITEA_SECURITY_CSRF_COOKIE_HTTP_ONLY
[[ -z "${GITEA_SECURITY_CSRF_COOKIE_HTTP_ONLY}" ]] && GITEA_SECURITY_CSRF_COOKIE_HTTP_ONLY="true"
