#!/usr/bin/env bash

declare -x GITEA_PICTURE_AVATAR_UPLOAD_PATH
[[ -z "${GITEA_PICTURE_AVATAR_UPLOAD_PATH}" ]] && GITEA_PICTURE_AVATAR_UPLOAD_PATH="${GITEA_BASE_PATH}/avatars"

declare -x GITEA_PICTURE_REPOSITORY_AVATAR_UPLOAD_PATH
[[ -z "${GITEA_PICTURE_REPOSITORY_AVATAR_UPLOAD_PATH}" ]] && GITEA_PICTURE_REPOSITORY_AVATAR_UPLOAD_PATH="${GITEA_BASE_PATH}/avatars/repo"

declare -x GITEA_PICTURE_REPOSITORY_AVATAR_FALLBACK
[[ -z "${GITEA_PICTURE_REPOSITORY_AVATAR_FALLBACK}" ]] && GITEA_PICTURE_REPOSITORY_AVATAR_FALLBACK="none"

declare -x GITEA_PICTURE_REPOSITORY_AVATAR_FALLBACK_IMAGE
[[ -z "${GITEA_PICTURE_REPOSITORY_AVATAR_FALLBACK_IMAGE}" ]] && GITEA_PICTURE_REPOSITORY_AVATAR_FALLBACK_IMAGE="/img/repo_default.png"

declare -x GITEA_PICTURE_AVATAR_MAX_WIDTH
[[ -z "${GITEA_PICTURE_AVATAR_MAX_WIDTH}" ]] && GITEA_PICTURE_AVATAR_MAX_WIDTH="4096"

declare -x GITEA_PICTURE_AVATAR_MAX_HEIGHT
[[ -z "${GITEA_PICTURE_AVATAR_MAX_HEIGHT}" ]] && GITEA_PICTURE_AVATAR_MAX_HEIGHT="3072"

declare -x GITEA_PICTURE_GRAVATAR_SOURCE
[[ -z "${GITEA_PICTURE_GRAVATAR_SOURCE}" ]] && GITEA_PICTURE_GRAVATAR_SOURCE="gravatar"

declare -x GITEA_PICTURE_AVATAR_MAX_FILE_SIZE
[[ -z "${GITEA_PICTURE_AVATAR_MAX_FILE_SIZE}" ]] && GITEA_PICTURE_AVATAR_MAX_FILE_SIZE="1048576"

declare -x GITEA_PICTURE_DISABLE_GRAVATAR
[[ -z "${GITEA_PICTURE_DISABLE_GRAVATAR}" ]] && GITEA_PICTURE_DISABLE_GRAVATAR="false"

declare -x GITEA_PICTURE_ENABLE_FEDERATED_AVATAR
[[ -z "${GITEA_PICTURE_ENABLE_FEDERATED_AVATAR}" ]] && GITEA_PICTURE_ENABLE_FEDERATED_AVATAR="false"
