#!/usr/bin/env bash

declare -x GITEA_LOG_ROOT_PATH
[[ -z "${GITEA_LOG_ROOT_PATH}" ]] && GITEA_LOG_ROOT_PATH="/var/log/gitea"

declare -x GITEA_LOG_MODE
[[ -z "${GITEA_LOG_MODE}" ]] && GITEA_LOG_MODE="console"

declare -x GITEA_LOG_BUFFER_LEN
[[ -z "${GITEA_LOG_BUFFER_LEN}" ]] && GITEA_LOG_BUFFER_LEN="10000"

declare -x GITEA_LOG_REDIRECT_MACARON_LOG
[[ -z "${GITEA_LOG_REDIRECT_MACARON_LOG}" ]] && GITEA_LOG_REDIRECT_MACARON_LOG="false"

declare -x GITEA_LOG_MACARON
[[ -z "${GITEA_LOG_MACARON}" ]] && GITEA_LOG_MACARON="console"

declare -x GITEA_LOG_ROUTER_LOG_LEVEL
[[ -z "${GITEA_LOG_ROUTER_LOG_LEVEL}" ]] && GITEA_LOG_ROUTER_LOG_LEVEL="Info"

declare -x GITEA_LOG_ROUTER
[[ -z "${GITEA_LOG_ROUTER}" ]] && GITEA_LOG_ROUTER="console"

declare -x GITEA_LOG_ENABLE_ACCESS_LOG
[[ -z "${GITEA_LOG_ENABLE_ACCESS_LOG}" ]] && GITEA_LOG_ENABLE_ACCESS_LOG="false"

declare -x GITEA_LOG_ACCESS_LOG_TEMPLATE
[[ -z "${GITEA_LOG_ACCESS_LOG_TEMPLATE}" ]] && GITEA_LOG_ACCESS_LOG_TEMPLATE='{{.Ctx.RemoteAddr}} - {{.Identity}} {{.Start.Format "[02/Jan/2006:15:04:05 -0700]" }} "{{.Ctx.Req.Method}} {{.Ctx.Req.RequestURI}} {{.Ctx.Req.Proto}}" {{.ResponseWriter.Status}} {{.ResponseWriter.Size}} "{{.Ctx.Req.Referer}}\" \"{{.Ctx.Req.UserAgent}}"'

declare -x GITEA_LOG_ACCESS
[[ -z "${GITEA_LOG_ACCESS}" ]] && GITEA_LOG_ACCESS="console"

declare -x GITEA_LOG_LEVEL
[[ -z "${GITEA_LOG_LEVEL}" ]] && GITEA_LOG_LEVEL="Info"

declare -x GITEA_LOG_STACKTRACE_LEVEL
[[ -z "${GITEA_LOG_STACKTRACE_LEVEL}" ]] && GITEA_LOG_STACKTRACE_LEVEL="None"

declare -x GITEA_LOG_X_FLAGS
[[ -z "${GITEA_LOG_X_FLAGS}" ]] && GITEA_LOG_X_FLAGS="stdflags"

declare -x GITEA_LOG_X_EXPRESSION
[[ -z "${GITEA_LOG_X_EXPRESSION}" ]] && GITEA_LOG_X_EXPRESSION=""

declare -x GITEA_LOG_X_PREFIX
[[ -z "${GITEA_LOG_X_PREFIX}" ]] && GITEA_LOG_X_PREFIX=""

declare -x GITEA_LOG_X_COLORIZE
[[ -z "${GITEA_LOG_X_COLORIZE}" ]] && GITEA_LOG_X_COLORIZE="false"

declare -x GITEA_LOG_CONSOLE_LEVEL
[[ -z "${GITEA_LOG_CONSOLE_LEVEL}" ]] && GITEA_LOG_CONSOLE_LEVEL=""

declare -x GITEA_LOG_CONSOLE_STDERR
[[ -z "${GITEA_LOG_CONSOLE_STDERR}" ]] && GITEA_LOG_CONSOLE_STDERR="false"

declare -x GITEA_LOG_FILE_LEVEL
[[ -z "${GITEA_LOG_FILE_LEVEL}" ]] && GITEA_LOG_FILE_LEVEL=""

declare -x GITEA_LOG_FILE_NAME
[[ -z "${GITEA_LOG_FILE_NAME}" ]] && GITEA_LOG_FILE_NAME=""

declare -x GITEA_LOG_FILE_ROTATE
[[ -z "${GITEA_LOG_FILE_ROTATE}" ]] && GITEA_LOG_FILE_ROTATE="true"

declare -x GITEA_LOG_FILE_MAX_LINES
[[ -z "${GITEA_LOG_FILE_MAX_LINES}" ]] && GITEA_LOG_FILE_MAX_LINES="1000000"

declare -x GITEA_LOG_FILEMAX_SIZE_SHIFT
[[ -z "${GITEA_LOG_FILEMAX_SIZE_SHIFT}" ]] && GITEA_LOG_FILEMAX_SIZE_SHIFT="28"

declare -x GITEA_LOG_FILE_DAILY_ROTATE
[[ -z "${GITEA_LOG_FILE_DAILY_ROTATE}" ]] && GITEA_LOG_FILE_DAILY_ROTATE="true"

declare -x GITEA_LOG_FILE_MAX_DAYS
[[ -z "${GITEA_LOG_FILE_MAX_DAYS}" ]] && GITEA_LOG_FILE_MAX_DAYS="7"

declare -x GITEA_LOG_FILE_COMPRESS
[[ -z "${GITEA_LOG_FILE_COMPRESS}" ]] && GITEA_LOG_FILE_COMPRESS="true"

declare -x GITEA_LOG_FILE_COMPRESSION_LEVEL
[[ -z "${GITEA_LOG_FILE_COMPRESSION_LEVEL}" ]] && GITEA_LOG_FILE_COMPRESSION_LEVEL="-1"

declare -x GITEA_LOG_CONN_LEVEL
[[ -z "${GITEA_LOG_CONN_LEVEL}" ]] && GITEA_LOG_CONN_LEVEL=""

declare -x GITEA_LOG_CONN_RECONNECT_ON_MSG
[[ -z "${GITEA_LOG_CONN_RECONNECT_ON_MSG}" ]] && GITEA_LOG_CONN_RECONNECT_ON_MSG="false"

declare -x GITEA_LOG_CONN_RECONNECT
[[ -z "${GITEA_LOG_CONN_RECONNECT}" ]] && GITEA_LOG_CONN_RECONNECT="false"

declare -x GITEA_LOG_CONN_PROTOCOL
[[ -z "${GITEA_LOG_CONN_PROTOCOL}" ]] && GITEA_LOG_CONN_PROTOCOL="tcp"

declare -x GITEA_LOG_CONN_ADDR
[[ -z "${GITEA_LOG_CONN_ADDR}" ]] && GITEA_LOG_CONN_ADDR=""

declare -x GITEA_LOG_SMTP_LEVEL
[[ -z "${GITEA_LOG_SMTP_LEVEL}" ]] && GITEA_LOG_SMTP_LEVEL=""

declare -x GITEA_LOG_SMTP_SUBJECT
[[ -z "${GITEA_LOG_SMTP_SUBJECT}" ]] && GITEA_LOG_SMTP_SUBJECT="Diagnostic message from server"

declare -x GITEA_LOG_SMTP_HOST
[[ -z "${GITEA_LOG_SMTP_HOST}" ]] && GITEA_LOG_SMTP_HOST=""

declare -x GITEA_LOG_SMTP_USER
[[ -z "${GITEA_LOG_SMTP_USER}" ]] && GITEA_LOG_SMTP_USER=""

declare -x GITEA_LOG_SMTP_PASSWD
[[ -z "${GITEA_LOG_SMTP_PASSWD}" ]] && GITEA_LOG_SMTP_PASSWD=""

declare -x GITEA_LOG_SMTP_RECEIVERS
[[ -z "${GITEA_LOG_SMTP_RECEIVERS}" ]] && GITEA_LOG_SMTP_RECEIVERS=""
