#!/usr/bin/env bash

declare -x GITEA_MIRROR_DEFAULT_INTERVAL
[[ -z "${GITEA_MIRROR_DEFAULT_INTERVAL}" ]] && GITEA_MIRROR_DEFAULT_INTERVAL="8h"

declare -x GITEA_MIRROR_MIN_INTERVAL
[[ -z "${GITEA_MIRROR_MIN_INTERVAL}" ]] && GITEA_MIRROR_MIN_INTERVAL="10m"
