#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

if [ -d ./custom.d ]
then
  for FILE in $(find ./custom.d -type f -iname \*.sh | sort)
  do
    source ${FILE}
  done
fi

STARTCMD="su-exec git /usr/bin/gitea web -c ${GITEA_CONFIG_FILE}"

echo "> starting gitea service"
exec ${STARTCMD}
