#!/usr/bin/env bash

declare -x GITEA_CORS_ENABLED
[[ -z "${GITEA_CORS_ENABLED}" ]] && GITEA_CORS_ENABLED="false"

declare -x GITEA_CORS_SCHEME
[[ -z "${GITEA_CORS_SCHEME}" ]] && GITEA_CORS_SCHEME="http"

declare -x GITEA_CORS_ALLOW_DOMAIN
[[ -z "${GITEA_CORS_ALLOW_DOMAIN}" ]] && GITEA_CORS_ALLOW_DOMAIN="*"

declare -x GITEA_CORS_ALLOW_SUBDOMAIN
[[ -z "${GITEA_CORS_ALLOW_SUBDOMAIN}" ]] && GITEA_CORS_ALLOW_SUBDOMAIN="false"

declare -x GITEA_CORS_METHODS
[[ -z "${GITEA_CORS_METHODS}" ]] && GITEA_CORS_METHODS="GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS"

declare -x GITEA_CORS_MAX_AGE
[[ -z "${GITEA_CORS_MAX_AGE}" ]] && GITEA_CORS_MAX_AGE="10m"

declare -x GITEA_CORS_ALLOW_CREDENTIALS
[[ -z "${GITEA_CORS_ALLOW_CREDENTIALS}" ]] && GITEA_CORS_ALLOW_CREDENTIALS="false"
