#!/usr/bin/env bash

declare -x GITEA_MARKUP_ASCIIDOC_ENABLED
[[ -z "${GITEA_MARKUP_ASCIIDOC_ENABLED}" ]] && GITEA_MARKUP_ASCIIDOC_ENABLED="true"

declare -x GITEA_MARKUP_ASCIIDOC_FILE_EXTENSIONS
[[ -z "${GITEA_MARKUP_ASCIIDOC_FILE_EXTENSIONS}" ]] && GITEA_MARKUP_ASCIIDOC_FILE_EXTENSIONS=".adoc,.asciidoc"

declare -x GITEA_MARKUP_ASCIIDOC_RENDER_COMMAND
[[ -z "${GITEA_MARKUP_ASCIIDOC_RENDER_COMMAND}" ]] && GITEA_MARKUP_ASCIIDOC_RENDER_COMMAND="asciidoc --out-file=- -"

declare -x GITEA_MARKUP_ASCIIDOC_IS_INPUT_FILE
[[ -z "${GITEA_MARKUP_ASCIIDOC_IS_INPUT_FILE}" ]] && GITEA_MARKUP_ASCIIDOC_IS_INPUT_FILE="false"
