#!/usr/bin/env bash

declare -x GITEA_TASK_QUEUE_TYPE
[[ -z "${GITEA_TASK_QUEUE_TYPE}" ]] && GITEA_TASK_QUEUE_TYPE="channel"

declare -x GITEA_TASK_QUEUE_LENGTH
[[ -z "${GITEA_TASK_QUEUE_LENGTH}" ]] && GITEA_TASK_QUEUE_LENGTH="1000"

declare -x GITEA_TASK_QUEUE_REDIS_HOST
[[ -z "${GITEA_TASK_QUEUE_REDIS_HOST}" ]] && GITEA_TASK_QUEUE_REDIS_HOST="redis:6379"

declare -x GITEA_TASK_QUEUE_REDIS_PASSWORD
[[ -z "${GITEA_TASK_QUEUE_REDIS_PASSWORD}" ]] && GITEA_TASK_QUEUE_REDIS_PASSWORD=""

declare -x GITEA_TASK_QUEUE_REDIS_DB
[[ -z "${GITEA_TASK_QUEUE_REDIS_DB}" ]] && GITEA_TASK_QUEUE_REDIS_DB="0"
